FROM node:20

WORKDIR /workspace/frontend/portal-empleado

COPY frontend/portal-empleado/package.json frontend/portal-empleado/package-lock.json ./
RUN npm install

COPY frontend/portal-empleado .

ENV CHOKIDAR_USEPOLLING=true

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
