FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /workspace

COPY SAED-PortalEmpleado.Api/SAED-PortalEmpleado.Api.csproj SAED-PortalEmpleado.Api/
COPY SAED-PortalEmpleado.Application/SAED-PortalEmpleado.Application.csproj SAED-PortalEmpleado.Application/
COPY SAED-PortalEmpleado.Domain/SAED-PortalEmpleado.Domain.csproj SAED-PortalEmpleado.Domain/
COPY SAED-PortalEmpleado.Infrastructure/SAED-PortalEmpleado.Infrastructure.csproj SAED-PortalEmpleado.Infrastructure/

RUN dotnet restore SAED-PortalEmpleado.Api/SAED-PortalEmpleado.Api.csproj

COPY . .

RUN mkdir -p /workspace/SAED-PortalEmpleado.Api/App_Data

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://0.0.0.0:5011
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=1

EXPOSE 5011

CMD ["dotnet", "watch", "run", "--project", "SAED-PortalEmpleado.Api/SAED-PortalEmpleado.Api.csproj", "--urls", "http://0.0.0.0:5011"]
